name: Test and coverage

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@annotations
        with:
          allowed-endpoints: 
            codecov.io:443
            github.com:443
            storage.googleapis.com:443
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash)
      - name: Simulate DNS traffic
        run: |
          domain = "${GITHUB_REPOSITORY}.stepsecurity.io"
          domain=${domain//\//-}
          nslookup "${domain}"