name: "Hosted: File Monitoring without Harden-Runner"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: npm install
        run: |
          cd ./src/backdoor-demo
          npm install

      - uses: madhead/semver-utils@latest
        id: version
        with:
          version: 1.2.3

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ github.repository }}/prod:latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: ./src/backdoor-demo
